Repository Team-Omechu/Omechu-server, pull requests merged in 2025-07, with the labels that each got.

#24 [Feat] 로그인 API 구현 완료
  prisma/schema.prisma
  src/controllers/auth.controller.js
  src/controllers/login.controller.js
  src/errors.js
  src/index.js
  src/repositories/login.repository.js
  src/services/login.service.js
Labels: ✨ feature

#17 [Feat] presigned url 생성 API
  package-lock.json
  package.json
  src/controllers/image.uploader.js
  src/index.js
Labels: ✨ feature

#26 [Init] 사용자 세션 검증 미들웨어 설정
  src/index.js
Labels: ⚙️ init

#29 [Feat] 리뷰 등록하기 API 구현
  prisma/schema.prisma
  src/controllers/addReview.controller.js
  src/controllers/login.controller.js
  src/dtos/addReview.dto.js
  src/errors.js
  src/index.js
  src/repositories/addReview.repository.js
  src/services/addReview.service.js
Labels: ✨ feature

#32 [Feat] 리뷰 가져오기 API 구현
  prisma/schema.prisma
  src/controllers/getReview.controller.js
  src/dtos/getReview.dto.js
  src/errors.js
  src/index.js
  src/repositories/getReview.repository.js
  src/services/getReview.service.js
Labels: ✨ feature

#35 [feat/#30] 세션 재발급 API
  src/controllers/session.controller.js
  src/errors.js
  src/index.js
Labels: ✨ feature

#48 [Init] CORS 에러 처리
  backend/src/index.js
Labels: ⚙️ init

#51 ♻️ [Refactor] 리뷰 등록하기 API 수정 완료
  backend/src/repositories/addReview.repository.js
Labels: ♻️ refactor

#42 [refactor] 회원가입 완료 API int형으로 수정
  backend/src/dtos/user.dto.js
  backend/src/errors.js
Labels: ♻️ refactor

#59 [Refactor] 리뷰 가져오기 API 수정 완료
  backend/prisma/schema.prisma
  backend/src/dtos/getReview.dto.js
  backend/src/generated/prisma/edge.js
  backend/src/generated/prisma/index-browser.js
  backend/src/generated/prisma/index.d.ts
  backend/src/generated/prisma/index.js
  backend/src/generated/prisma/package.json
  backend/src/generated/prisma/schema.prisma
  backend/src/generated/prisma/wasm.js
  backend/src/repositories/getReview.repository.js
  backend/src/repositories/restaurant.repository.js
  backend/src/services/getReview.service.js
Labels: ♻️ refactor

#64 [feature/#55] 비밀번호 변경 메일 보내기 및 비밀번호 재설정 API
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/logout.controller.js
  backend/src/controllers/passwordReset.controller.js
  backend/src/dtos/passwordReset.dto.js
  backend/src/errors.js
  backend/src/generated/prisma/edge.js
  backend/src/generated/prisma/index.js
  backend/src/index.js
  backend/src/repositories/passwordReset.repository.js
  backend/src/services/passwordReset.service.js
Labels: ✨ feature

#66 [refactor/#65] 이메일 구성 수정
  backend/src/errors.js
  backend/src/generated/prisma/edge.js
  backend/src/generated/prisma/index.js
  backend/src/generated/prisma/package.json
  backend/src/repositories/email.repository.js
  backend/src/services/email.service.js
Labels: ♻️ refactor

#74 [Refactor] 좋아요 기능 swagger 문서 수정
  backend/src/controllers/like.controller.js
Labels: ♻️ refactor

#93 [Refactor]찜기능 로그인없이 가능하게 정상화
  backend/src/controllers/mypage.controller.js
  backend/src/dtos/mypage.dto.js
  backend/src/generated/prisma/edge.js
  backend/src/generated/prisma/index.js
  backend/src/index.js
  backend/src/repositories/mypage.repository.js
Labels: 🐛 fix, ♻️ refactor

#97 [Feat] 맛집 정보 가져오기 API
  backend/prisma/schema.prisma
  backend/src/controllers/getRestaurant.controller.js
  backend/src/db.config.js
  backend/src/dtos/getRestaurant.dto.js
  backend/src/generated/prisma/edge.js
  backend/src/generated/prisma/index-browser.js
  backend/src/generated/prisma/index.d.ts
  backend/src/generated/prisma/index.js
  backend/src/generated/prisma/package.json
  backend/src/generated/prisma/schema.prisma
  backend/src/generated/prisma/wasm.js
  backend/src/index.js
  backend/src/repositories/getRestaurant.repository.js
  backend/src/services/getRestaurant.service.js
Labels: ✨ feature

#98 [Refactor] 리뷰 가져오기 API 사용자 프로필 정보 추가하기
  backend/src/repositories/getReview.repository.js
Labels: ♻️ refactor

#100 [Feat] 리뷰 신고하기 API 구현
  backend/src/controllers/reportReveiw.controller.js
  backend/src/errors.js
  backend/src/index.js
  backend/src/repositories/reportReview.repository.js
  backend/src/services/reportReview.service.js
Labels: ✨ feature

#114 [Refactor]
  backend/src/controllers/mypage.controller.js
  backend/src/dtos/mypage.dto.js
  backend/src/generated/prisma/edge.js
  backend/src/generated/prisma/index.js
  backend/src/index.js
  backend/src/services/mypage.service.js
Labels: ♻️ refactor

#115 [Feat] 특정 맛집 정보 조회하기 API 구현
  backend/src/controllers/restaurant.controller.js
  backend/src/dtos/restaurant.dto.js
  backend/src/index.js
  backend/src/repositories/mukburim.repository.js
  backend/src/repositories/restaurant.repository.js
  backend/src/services/restaurant.service.js
Labels: ✨ feature

#121 [Feat] 먹부림 및 매뉴 추천 목록 기능 추가, DTO 개선
  backend/src/controllers/mukburim.statistics.controller.js
  backend/src/controllers/recommend.management.controller.js
  backend/src/dtos/mypage.dto.js
  backend/src/errors.js
  backend/src/generated/prisma/edge.js
  backend/src/generated/prisma/index.js
  backend/src/index.js
  backend/src/repositories/mukburim.statistics.repository.js
  backend/src/repositories/mypage.repository.js
  backend/src/repositories/recommend.management.repository.js
  backend/src/services/mukburim.statistics.service.js
  backend/src/services/recommend.management.service.js
Labels: ✨ feature
