Repository Team-Omechu/Omechu-server, pull requests merged in 2025-08, with the labels that each got.

#125 [Fix] 내가 등록한 맛집 조회 API 수정
  backend/src/controllers/getRestaurant.controller.js
  backend/src/controllers/mypage.controller.js
  backend/src/dtos/mypage.dto.js
  backend/src/errors.js
  backend/src/generated/prisma/edge.js
  backend/src/generated/prisma/index.js
  backend/src/index.js
  backend/src/repositories/mypage.repository.js
  backend/src/services/mypage.service.js
Labels: 🐛 fix

#143 [Refactor] 마이페이지 JWT 토큰으로 변경에 따른 API 수정
  backend/src/controllers/mukburim.statistics.controller.js
  backend/src/controllers/mypage.controller.js
  backend/src/controllers/recommend.management.controller.js
  backend/src/index.js
Labels: ♻️ refactor

#150 [Feat] 메뉴 자동완성 API 구현 완료
  backend/src/controllers/suggestions.controller.js
  backend/src/errors.js
  backend/src/index.js
  backend/src/repositories/suggestions.repository.js
  backend/src/services/suggestions.service.js
Labels: ✨ feature

#152 [Refactor] 맛집 가져오기 API 수정 완료
  backend/src/controllers/getSearchRestaurant.controller.js
  backend/src/dtos/getSearchRestaurant.dto.js
  backend/src/repositories/getSearchRestaurant.repository.js
Labels: ♻️ refactor

#156 [Feature] 찜 삭제 기능 추가, 409 에러 추가
  backend/src/controllers/mypage.controller.js
  backend/src/errors.js
  backend/src/index.js
  backend/src/repositories/mypage.repository.js
  backend/src/services/mypage.service.js
Labels: ✨ feature
